const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const properties={};let token={aud:'test-client',sub:'verified-account',email_verified:'true',exp:Math.floor(Date.now()/1000)+3600};
const context={PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k],setProperty:(k,v)=>properties[k]=v})},UrlFetchApp:{fetch:()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify(token)})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})}};
vm.createContext(context);vm.runInContext(fs.readFileSync('Google-Apps-Script/Code.gs','utf8'),context);
assert.equal(context.doGet({parameter:{action:'load'}}).ok,false,'private GET loads denied');
assert.equal(context.doPost({postData:{contents:JSON.stringify({action:'save',credential:'token',data:{blocks:[{id:'private'}]}})}}).ok,false,'unconfigured requests fail closed');
properties.OAUTH_CLIENT_ID='test-client';
let result=context.doPost({postData:{contents:JSON.stringify({action:'save',credential:'token',data:{blocks:[{id:'private'}]}})}});
assert.equal(result.ok,false);assert.match(result.error,/user's Google Drive/,'backend refuses private data even for authenticated users');
token={...token,aud:'wrong-client'};
assert.equal(context.doPost({postData:{contents:JSON.stringify({action:'publish',credential:'token',data:{}})}}).ok,false,'wrong Google client rejected');
const source=fs.readFileSync('Google-Apps-Script/Code.gs','utf8');
assert(source.includes('body.token'));assert(source.includes('ownedRow'),'live publishing updates an owned token instead of changing its URL');
console.log('PASS backend: private data refused, identity validation retained, live public token updates supported');
