const assert=require('node:assert/strict');
const {chromium}=require(process.env.BEDO_PLAYWRIGHT_PATH);
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage(),base=process.env.BEDO_TEST_BASE||'http://localhost:8766',errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{localStorage.setItem('bedo-auth-user',JSON.stringify({sub:'checklist-user'}));localStorage.setItem('bedo-auth-session','session');localStorage.setItem('bedo-calendar-choice','fresh');localStorage.setItem('bedo-tour-state',JSON.stringify({completed:true}));localStorage.setItem('bedo-ideas','[]');});
 await page.goto(base+'/?app=1',{waitUntil:'domcontentloaded'});await page.locator('.bd-month').first().waitFor();await page.locator('#bd-fab').click();await page.locator('[data-quick-mode=checklist]').click();await page.locator('[name=text]').fill('Things to remember');let inputs=page.locator('[name=checkText]');await inputs.first().fill('Priority');await page.locator('[data-action=add-check-item]').click();await page.locator('[data-action=add-check-item]').click();inputs=page.locator('[name=checkText]');await inputs.nth(1).fill('Next list');await inputs.nth(2).fill('Strikethrough check');await page.locator('[data-checklist-row]').nth(2).locator('[type=checkbox]').check();await page.locator('#bd-note-form .bd-primary').click();
 await page.locator('[data-page=brainstorm]:visible').click();const note=page.locator('.bd-note').filter({hasText:'Things to remember'});await note.waitFor();let labels=await note.locator('.bd-note-checklist li span').allTextContents();assert.deepEqual(labels,['Priority','Next list','Strikethrough check']);assert((await note.locator('.bd-note-checklist li').nth(2).getAttribute('class')).includes('checked'));assert((await note.locator('.bd-note-checklist li').nth(2).locator('span').evaluate(el=>getComputedStyle(el).textDecorationLine)).includes('line-through'));
 await note.locator('[data-toggle-note-item]').first().click();labels=await note.locator('.bd-note-checklist li span').allTextContents();assert.deepEqual(labels,['Next list','Priority','Strikethrough check'],'checked items move below every unchecked item');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-ideas'))[0]);assert.equal(saved.text,'Things to remember');assert.equal(saved.checklist.filter(item=>item.checked).length,2);assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS floating checklist notes, mixed text, completion, strikethrough and unfinished-first ordering');
})().catch(error=>{console.error(error);process.exit(1)});
