/* Run: node tests/redesign.cjs. Playwright is installed in a temporary tools directory. */
const assert = require('node:assert/strict');
const path = require('node:path');
const { chromium } = require(process.env.BEDO_PLAYWRIGHT_PATH || path.join(process.env.TEMP, 'bedo-ui-tests/node_modules/playwright'));
const base = process.env.BEDO_TEST_BASE || 'http://localhost:8765';
(async () => {
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  try {
    for (const [name,width,height] of [['mobile',390,844],['tablet',820,1180],['desktop',1440,1000]]) {
      const context=await browser.newContext({viewport:{width,height},hasTouch:name!=='desktop',timezoneId:name==='desktop'?'America/Los_Angeles':'Asia/Makassar'});
      const page=await context.newPage(),errors=[];
      await page.clock.install({time:new Date('2026-12-31T12:00:00Z')});
      page.on('pageerror',e=>errors.push(e.message));
      await page.goto(base+'/',{waitUntil:'domcontentloaded'});
      await page.locator('.bd-hero').waitFor();
      assert.equal(await page.title(),'bedo');
      assert.equal(await page.locator('#bedo-intro-title').textContent(),'Which one are you?');
      assert.equal(await page.locator('.bd-bedo-types article').count(),2);
      assert.equal(await page.evaluate(()=>getComputedStyle(document.body).overflow),'hidden','outer landing scroll locked');
      assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),true,'only landing has a scrollbar');
      assert.equal(await page.locator('#root').isVisible(),false,'underlying app is hidden');
      const supplied=await (await page.request.get(base+'/favicon.svg')).text();
      const paths=[...supplied.matchAll(/<path d="([^"]+)"/g)].map(m=>m[1]);
      assert.deepEqual(await page.locator('.bd-landing-nav .bd-logo-svg path').evaluateAll(els=>els.map(el=>el.getAttribute('d'))),paths,'main logo uses exact supplied SVG paths');
      const texts=await page.locator('#features article>span').allTextContents();assert(texts.includes('💭')&&texts.includes('💼')&&!texts.includes('🫧')&&!texts.includes('🌈'));
      assert.equal(await page.locator('.bd-landing').evaluate((el,previous)=>el.textContent.toLowerCase().includes(previous),['block','day'].join('')),false,'no old branding in landing');
      await page.locator('.bd-landing').evaluate(el=>el.scrollTop=400);
      assert.equal(await page.evaluate(()=>scrollY),0,'scrolling landing does not scroll page behind it');
      await page.locator('.bd-landing').evaluate(el=>el.scrollTop=0);
      assert.equal(await page.evaluate(()=>document.querySelector('.bd-landing').scrollWidth<=innerWidth),true,'landing fits viewport');
      await page.screenshot({path:path.join(process.env.TEMP,`bedo-landing-${name}.png`)});
      await page.evaluate(()=>localStorage.setItem('bedo-blocks',JSON.stringify([{id:'real-private',title:'Original personal data',date:'2026-9-1',start:8,duration:1}])));
      await page.locator('#bd-demo-cta').click();
      await page.waitForURL('**/?demo=1');
      await page.locator('.bd-month').waitFor();
      assert.equal(await page.locator('.bd-segments [data-view=month]').getAttribute('class'),'active');
      assert(await page.locator('.bd-day-celebration').count()>0,'demo includes completed-day examples');
      assert.equal(await page.locator('.bd-day-completed').first().textContent(),'🎯');
      assert.equal(await page.locator('.bd-day-incomplete').first().textContent(),'🎗️');
      assert.equal(await page.locator('.bd-month-day.today .bd-day-incomplete').count(),0,'no ribbon on unfinished today');
      assert.equal(await page.evaluate(()=>{const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());return Array.from(document.querySelectorAll('.bd-day-incomplete')).every(el=>{const [y,m,d]=el.closest('[data-date]').dataset.date.split('-').map(Number);return new Date(y,m-1,d)<today;});}),true,'ribbons only mark past unfinished days');
      assert.equal(await page.locator('.bd-day-status').first().evaluate(el=>getComputedStyle(el).fontStyle),'normal','status emoji is not italic');
      assert.equal(await page.evaluate(()=>Array.from(document.querySelectorAll('.bd-month-day')).filter(el=>el.getAttribute('aria-label').includes(', 0 blocks')).some(el=>el.querySelector('.bd-day-status'))),false,'empty days have no status marker');
      await page.screenshot({path:path.join(process.env.TEMP,`bedo-calendar-status-${name}.png`)});
      await page.locator('.bd-month-day.today').click();
      await page.locator('.bd-block').first().waitFor();
      assert.equal(await page.locator('.bd-block').count(),8);
      assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')).length>=78),'two weeks of demo blocks');
      await page.screenshot({path:path.join(process.env.TEMP,`bedo-day-${name}.png`)});
      await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem('bedo-blocks'));data.push({...data[0],id:'other-day-occurrence',date:'2026-10-1',recurring:true});localStorage.setItem('bedo-blocks',JSON.stringify(data));});
      await page.reload({waitUntil:'domcontentloaded'});await page.locator('.bd-month-day.today').click();
      const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
      const handle=page.locator('[data-drag="demo-1"]'),box=await handle.boundingBox();
      await page.mouse.move(box.x+box.width/2,box.y+15);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+87,{steps:10});await page.mouse.up();
      const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
      assert(Math.abs(after[0].start-before[0].start-1)<.001,'drag moves block by one hour');
      assert.equal(after[0].date,before[0].date,'drag retains date');
      assert.deepEqual(after.slice(1),before.slice(1),'other occurrences stay unchanged');
      if(name==='mobile'){
        const touch=await context.newCDPSession(page),target=await page.locator('[data-drag="demo-1"]').boundingBox();
        const x=target.x+target.width/2,y=target.y+15;
        await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
        await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+36}]});
        await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
        const touched=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
        assert(Math.abs(touched[0].start-after[0].start-.5)<.001,'touch drag moves by half an hour');
        assert.deepEqual(touched.slice(1),after.slice(1),'touch drag preserves other days');
      }
      await page.locator('[data-filter=Work]').click();assert.equal(await page.locator('.bd-block').count(),2);
      await page.locator('[data-filter=All]').click();
      await page.locator('[data-action=add]').click();
      await page.locator('[name=title]').fill('Repeated test');await page.locator('[name=repeat]').selectOption('weekly');
      await page.locator('#bd-block-form .bd-primary').click();
      assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')).filter(b=>b.title==='Repeated test').length),4);
      await page.locator('.bd-segments [data-view=week]').click();await page.locator('.bd-week-strip').waitFor();
      await page.locator('[data-page=brainstorm]:visible').click();await page.locator('.bd-note').waitFor();
      await page.locator('#bd-fab').click();await page.locator('[name=text]').fill('A fresh thought');await page.locator('#bd-note-form .bd-primary').click();
      assert.equal(await page.locator('.bd-note').count(),2);
      await page.locator('[data-schedule-note]').first().click();assert.equal(await page.locator('[name=title]').inputValue(),'A fresh thought');
      await page.locator('[data-action=close]').click();
      await page.locator('[data-page=insights]:visible').click();await page.locator('.bd-bars').waitFor();
      await page.locator('[data-page=settings]:visible').click();await page.locator('[data-settings-section=appearance]').click();await page.locator('[data-palette=berry]').click();
      assert.equal(await page.locator('#bd-account-card + #bd-app-guide').count(),1,'guide sits immediately under account');
      await page.locator('[data-settings-section=guide]').click();
      assert.equal(await page.locator('#bd-app-guide details').count(),0);
      assert(await page.locator('[data-action=tour]').isVisible());
      await page.locator('[data-settings-section=appearance]').click();
      await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'berry');
      const surfaces=[];
      for(const mode of ['light','dark']){
        if(await page.evaluate(()=>document.documentElement.dataset.mode)!==mode) await page.locator('[data-action=theme]').click();
        for(const palette of ['sage','ocean','berry','neutral']){
          await page.locator(`[data-palette=${palette}]`).click();
          const colors=await page.evaluate(()=>({bg:getComputedStyle(document.body).backgroundColor,card:getComputedStyle(document.querySelector('.bd-card')).backgroundColor,logo:getComputedStyle(document.querySelector('.bd-logo-svg g[fill]')).fill,logoBg:getComputedStyle(document.querySelector('.bd-logo-svg>rect')).fill}));
          if(mode==='dark')assert.notEqual(colors.bg,colors.card,'dark background and cards have distinct colors');
          else assert.equal(colors.card,'rgb(255, 255, 255)','light cards are white');
          assert.notEqual(colors.logo,colors.logoBg,'logo lettering contrasts with tile');
          if(mode==='light')assert.equal(colors.bg,'rgb(255, 255, 255)','preset surfaces are white');
          if(palette==='neutral'){assert.equal(colors.logoBg,mode==='dark'?'rgb(98, 104, 116)':'rgb(116, 123, 135)','neutral logo is grey, not green');assert.equal(colors.logo,'rgb(255, 255, 255)','neutral logo lettering remains white');}
          if(mode==='dark') {
            assert.equal(colors.logo,'rgb(255, 255, 255)','dark-mode face is bright white');
            assert.equal(await page.locator('.bd-top .bd-logo-svg path').count(),3,'same supplied logo is used in dark mode');
            const rgb=colors.logoBg.match(/\d+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});
            const luminance=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;
            assert(1.05/(luminance+.05)>=4.5,'dark-mode face has strong contrast');
          }
          surfaces.push(colors.bg);
          await page.screenshot({path:path.join(process.env.TEMP,`bedo-theme-${name}-${mode}-${palette}.png`)});
        }
      }
      assert.equal(new Set(surfaces).size,5,'white light surfaces and four dark palettes');
      assert.equal(await page.locator('.bd-brand .bd-logo-svg').count(),1,'desktop supplied logo rendered');
      assert.equal(await page.locator('.bd-logo-svg').first().getAttribute('viewBox'),'0 0 1500 1499.999933','supplied SVG proportions preserved');
      const customBackgrounds=[];
      for(const mode of ['light','dark']){
        if(await page.evaluate(()=>document.documentElement.dataset.mode)!==mode)await page.locator('[data-action=theme]').click();
        for(const hex of ['#7c5ce7','#ffffff','#000000','#ffff00']){
          await page.locator('#bd-custom-hex').fill(hex);await page.locator('[data-action=custom-color]').click();
          assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom');
          assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-profile')).customColor),hex);
          const colors=await page.evaluate(()=>({bg:getComputedStyle(document.body).backgroundColor,card:getComputedStyle(document.querySelector('.bd-card')).backgroundColor,ink:getComputedStyle(document.querySelector('.bd-logo-svg g[fill]')).fill,logo:getComputedStyle(document.querySelector('.bd-logo-svg>rect')).fill,primary:getComputedStyle(document.querySelector('#bd-settings>.bd-primary')).backgroundColor,buttonText:getComputedStyle(document.querySelector('#bd-settings>.bd-primary')).color}));
          const luminance=rgb=>{const c=rgb.match(/\d+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return c[0]*.2126+c[1]*.7152+c[2]*.0722;};
          const ratio=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
          assert(ratio(colors.ink,colors.logo)>=4.5,'custom logo remains readable');
          assert(ratio(colors.primary,colors.buttonText)>=4.5,'custom buttons remain readable');
          assert.notEqual(colors.bg,colors.card);customBackgrounds.push(colors.bg);
          if(hex==='#7c5ce7')await page.screenshot({path:path.join(process.env.TEMP,`bedo-custom-${name}-${mode}.png`)});
        }
      }
      assert.equal(new Set(customBackgrounds).size,8,'custom color tints backgrounds in both modes');
      await page.locator('#bd-custom-hex').fill('invalid');await page.locator('[data-action=custom-color]').click();
      assert.equal(await page.locator('#bd-custom-hex').getAttribute('aria-invalid'),'true','invalid hex rejected');
      assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-profile')).customColor),'#ffff00','invalid input does not overwrite saved color');
      await page.locator('#bd-custom-hex').fill('#abc');await page.locator('[data-action=custom-color]').click();
      assert.equal(await page.locator('#bd-custom-color').inputValue(),'#aabbcc','short hex expands and syncs picker');
      await page.reload({waitUntil:'domcontentloaded'});
      assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom','custom theme survives reload');
      await page.locator('[data-page=settings]:visible').click();await page.locator('[data-settings-section=appearance]').click();
      assert.equal(await page.locator('#bd-custom-hex').inputValue(),'#aabbcc');
      await page.locator('.bd-palettes [data-palette=neutral]').click();
      assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--bg')),'','presets clear custom overrides');
      await page.reload({waitUntil:'domcontentloaded'});
      assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'neutral','palette survives reload');
      assert.equal(await page.evaluate(()=>document.documentElement.dataset.mode),'dark','dark mode survives reload');
      await page.locator('[data-page=settings]:visible').click();await page.locator('[data-settings-section=appearance]').click();
      const fab=await page.locator('#bd-fab').boundingBox();await page.mouse.move(fab.x+20,fab.y+20);await page.mouse.down();await page.mouse.move(fab.x-80,fab.y-80,{steps:6});await page.mouse.up();
      assert.equal(await page.locator('#bd-dialog').count(),0,'dragging FAB does not open dialog');
      assert(await page.evaluate(()=>Boolean(localStorage.getItem('bedo-quick-note-position'))),'FAB position saved');
      await page.locator('#bd-fab').click();await page.locator('#bd-note-form').waitFor();await page.locator('[data-action=close]').click();
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'app fits viewport');
      await page.evaluate(()=>{
        const data=JSON.parse(localStorage.getItem('bedo-blocks')),today=localStorage.getItem('bedo-demo-anchor-date');
        data.forEach(b=>{if(b.date===today)b.completed=true;});localStorage.setItem('bedo-blocks',JSON.stringify(data));
      });
      await page.reload({waitUntil:'domcontentloaded'});
      assert.equal(await page.locator('.bd-month-day.today .bd-day-celebration').count(),1,'all completed shows celebration');
      assert.equal(await page.locator('.bd-month-day.today .bd-day-status').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)','no Today highlight oval behind emoji');
      assert.notEqual(await page.locator('.bd-month-day.today .bd-date-number').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)','date number still highlights Today');
      await page.locator('.bd-month-day.today').click();
      await page.locator('[data-complete="demo-5"]').click();
      await page.locator('.bd-segments [data-view=month]').click();
      await page.locator('[data-filter=Wellness]').click();
      assert.equal(await page.locator('.bd-month-day.today .bd-day-completed').count(),0,'hidden incomplete Work block prevents celebration');
      assert.equal(await page.locator('.bd-month-day.today .bd-day-incomplete').count(),0,'unfinished today stays unmarked');
      const rollingBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
      await page.clock.setSystemTime(new Date(await page.evaluate(()=>Date.now()+86400000)));
      await page.clock.runFor(1100);
      const rollingAfter=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
      assert.deepEqual(rollingAfter,rollingBefore.map(b=>{const [y,m,d]=b.date.split('-').map(Number),day=new Date(y,m-1,d+1,12);return {...b,date:`${day.getFullYear()}-${day.getMonth()+1}-${day.getDate()}`};}),'open demo rolls across midnight/year and retains edits');
      await page.clock.setSystemTime(new Date(await page.evaluate(()=>Date.now()+35*86400000)));
      await page.reload({waitUntil:'domcontentloaded'});
      const returning=await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks')));
      assert.deepEqual(returning,rollingAfter.map(b=>{const [y,m,d]=b.date.split('-').map(Number),day=new Date(y,m-1,d+35,12);return {...b,date:`${day.getFullYear()}-${day.getMonth()+1}-${day.getDate()}`};}),'returning demo rolls across months without losing blocks');
      await page.locator('.bd-exit').click();await page.waitForURL(base+'/');
      assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-blocks'))[0].id),'real-private','demo exit restores original data');
      assert.deepEqual(errors,[],`no page errors at ${name} width`);
      console.log(`PASS ${name}: calendar, drag, notes, insights, neutral theme, dark logo, guide, celebrations, rolling dates, demo restore`);
      await context.close();
    }
    const actual=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Pacific/Auckland'});
    await actual.route('https://script.google.com/**',route=>route.abort());
    const page=await actual.newPage();
    await page.clock.install({time:new Date('2026-11-30T08:00:00Z')});
    await page.goto(base+'/',{waitUntil:'domcontentloaded'});
    await page.evaluate(()=>{
      const now=new Date(),date=`${now.getFullYear()}-${now.getMonth()+1}-${now.getDate()}`;
      localStorage.setItem('bedo-auth-user',JSON.stringify({sub:'local-ui-test-only',email:'test@example.test'}));
      localStorage.setItem('bedo-appscript','false');
      localStorage.setItem('bedo-profile',JSON.stringify({name:'Private test',theme:'sand'}));
      localStorage.setItem('bedo-theme',JSON.stringify('dark'));
      localStorage.setItem('bedo-blocks',JSON.stringify([{id:'private-work',title:'Work block',category:'Work',date,start:9,duration:1,completed:true},{id:'private-personal',title:'Personal block',category:'Personal',date,start:12,duration:1,completed:false}]));
    });
    await page.goto(base+'/?app=1',{waitUntil:'domcontentloaded'});
    assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'neutral','previous gold preference migrates to neutral');
    assert.equal(await page.locator('.bd-month-day.today .bd-day-completed').count(),0);
    assert.equal(await page.locator('.bd-month-day.today .bd-day-incomplete').count(),0);
    await page.locator('.bd-month-day.today').click();
    await page.locator('[data-complete=private-personal]').click();
    await page.locator('.bd-segments [data-view=month]').click();
    assert.equal(await page.locator('.bd-month-day.today .bd-day-celebration').count(),1,'completion celebration works outside demo');
    const privateBefore=await page.evaluate(()=>localStorage.getItem('bedo-blocks'));
    await page.clock.setSystemTime(new Date(await page.evaluate(()=>Date.now()+86400000)));
    await page.clock.runFor(1100);
    assert.equal(await page.evaluate(()=>localStorage.getItem('bedo-blocks')),privateBefore,'real schedules never roll like demo data');
    await page.locator('[data-page=settings]:visible').click();await page.locator('[data-settings-section=appearance]').click();
    assert.equal(await page.locator('#bd-account-card + #bd-app-guide').count(),1,'guide also appears in actual app');
    assert.equal(await page.locator('.bd-palettes [data-palette=neutral]').count(),1);
    await page.locator('#bd-custom-color').evaluate(input=>{input.value='#2ab6bc';input.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.equal(await page.locator('#bd-custom-hex').inputValue(),'#2ab6bc','picker updates hex field');
    await page.locator('[data-action=custom-color]').click();
    assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom','custom color works outside demo');
    await page.locator('#bd-custom-hex').fill('#369');
    await page.locator('#bd-settings > .bd-primary').click();
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bedo-profile')).customColor),'#336699','saving preferences also saves custom color');
    await page.reload({waitUntil:'domcontentloaded'});
    assert.equal(await page.evaluate(()=>document.documentElement.dataset.palette),'custom');
    console.log('PASS actual app: neutral migration, completion celebration, guide, and private dates unchanged');
    await actual.close();
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
