const assert=require('node:assert/strict');
const {chromium}=require(process.env.BEDO_PLAYWRIGHT_PATH);
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,timezoneId:'Asia/Makassar'});
 await page.route('**/auth-config.js',r=>r.fulfill({body:'window.BEDO_GOOGLE_CLIENT_ID="";'}));
 await page.route('**/accounts.google.com/gsi/client',r=>r.fulfill({body:''}));
 await page.goto((process.env.BEDO_TEST_BASE||'http://localhost:8766')+'/',{waitUntil:'domcontentloaded'});
 await page.locator('.bd-preview').waitFor();
 assert.equal(await page.locator('.bd-preview').evaluate(el=>getComputedStyle(el).transform),'none');
 assert.equal(await page.locator('.bd-preview .peach').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(242, 204, 33)');
 await page.locator('#bd-demo-cta').click();await page.locator('.bd-month-day.today').click();
 assert.equal(await page.locator('[data-action=add],[data-action=note]').count(),0);
 let timeline=page.locator('.bd-timeline:visible');
 assert.equal(await timeline.evaluate(el=>getComputedStyle(el).overflowY),'visible');
 await page.mouse.wheel(0,500);await page.waitForTimeout(100);
 assert(await page.evaluate(()=>scrollY)>0);assert.equal(await timeline.evaluate(el=>el.scrollTop),0);
 await page.locator('[data-view=week]').click();timeline=page.locator('.bd-timeline:visible');
 assert.equal(await timeline.evaluate(el=>getComputedStyle(el).overflowY),'visible');
 await page.locator('[data-view=month]').click();
 await page.locator('#bd-more-months').scrollIntoViewIfNeeded();await page.waitForTimeout(200);
 assert(await page.locator('.bd-month-section').count()>1,'scroll loads later months');
 const first=await page.locator('.bd-month-section').first().getAttribute('data-month');
 await page.locator('[data-action=earlier-month]').click();
 assert.notEqual(await page.locator('.bd-month-section').first().getAttribute('data-month'),first);
 await page.clock.install();
 await page.mouse.move(20,100);await page.clock.fastForward(46000);
 assert(await page.locator('#bd-idle-hint').isVisible(),'pause shows a thought bubble');
 assert.equal(await page.locator('#bd-idle-hint').textContent(),'Got a thought to write?');
 await page.locator('#bd-fab').click();assert.equal(await page.locator('#bd-idle-hint').isVisible(),false);
 await page.clock.fastForward(240000);assert.equal(await page.locator('#bd-idle-hint').isVisible(),false,'no prompts during input');
 await page.locator('[data-action=close]').click();
 await page.screenshot({path:require('node:path').join(process.env.TEMP,'bedo-single-scroll-mobile.png')});
 await browser.close();console.log('PASS flat preview, block colors, floating-only quick creation, single page scroll, month loading and idle prompts');
})().catch(e=>{console.error(e);process.exit(1)});
