/* Local-first sync to a private app-data file owned by the signed-in Google account. */
(function(){
'use strict';
if(new URLSearchParams(location.search).has('demo'))return;
const api=localStorage.getItem('bedo-sync-url')||window.BEDO_API_URL,fileName='bedo-data.json';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const keys={blocks:'bedo-blocks',ideas:'bedo-ideas',dailyNotes:'bedo-daily-notes',routines:'bedo-routines',templates:'bedo-block-templates'};
let status={state:'local',message:'Autosaved on this device.'},initialized=false,busy=false,timer,fileId=null;
function notify(state,message){status={state,message,lastSavedAt:localStorage.getItem('bedo-last-sync')};dispatchEvent(new CustomEvent('bedo-sync-status'));}
function data(){return {...Object.fromEntries(Object.entries(keys).map(([k,v])=>[k,read(v,[])])),settings:[{id:'preferences',theme:read('bedo-theme','light'),profile:read('bedo-profile',{}),tour:read('bedo-tour-state',null),lastView:read('bedo-last-view',null)}],updatedAt:localStorage.getItem('bedo-local-updated-at')||null};}
function backupLocal(){const snapshot=data(),signature=JSON.stringify(snapshot),backups=read('bedo-autosave-backups',[]);if(backups[0]?.signature===signature)return;backups.unshift({savedAt:new Date().toISOString(),signature,data:snapshot});localStorage.setItem('bedo-autosave-backups',JSON.stringify(backups.slice(0,12)));}
async function drive(path,options={}){const interactive=Boolean(options.interactive);delete options.interactive;const token=await window.BedoAuth.requestDriveAccess(interactive),response=await fetch('https://www.googleapis.com'+path,{...options,headers:{...(options.headers||{}),Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)});if(!response.ok){const body=await response.json().catch(()=>({}));throw Error(body.error?.message||'Google Drive is unavailable.');}return response;}
async function locate(){if(fileId)return fileId;const result=await (await drive('/drive/v3/files?spaces=appDataFolder&pageSize=10&fields=files(id,name,modifiedTime)&q='+encodeURIComponent("name='"+fileName+"' and trashed=false"))).json();fileId=result.files?.[0]?.id||null;return fileId;}
async function loadDrive(){const id=await locate();if(!id)return null;return (await drive('/drive/v3/files/'+encodeURIComponent(id)+'?alt=media')).json();}
async function saveDrive(snapshot){const now=new Date().toISOString();snapshot={...snapshot,updatedAt:snapshot.updatedAt||now,savedAt:now};const id=await locate();if(!id){const form=new FormData();form.append('metadata',new Blob([JSON.stringify({name:fileName,parents:['appDataFolder']})],{type:'application/json'}));form.append('file',new Blob([JSON.stringify(snapshot)],{type:'application/json'}));fileId=(await (await drive('/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',body:form})).json()).id;}else await drive('/upload/drive/v3/files/'+encodeURIComponent(id)+'?uploadType=media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});localStorage.setItem('bedo-sync-base',JSON.stringify(snapshot));return snapshot.savedAt;}
async function updateLiveShare(snapshot){const share=read('bedo-share',{}),session=localStorage.getItem('bedo-auth-session');if(!share.token||!share.live||!session)return;const day=key=>{const [y,m,d]=String(key).split('-').map(Number);return Date.UTC(y,m-1,d);},from=day(share.from),to=day(share.to),inRange=b=>day(b.date)>=from&&day(b.date)<=to,response=await fetch(api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'publish',session,token:share.token,data:{profile:snapshot.settings?.[0]?.profile||{},blocks:snapshot.blocks.filter(inRange),from:share.from,to:share.to}})}),result=await response.json();if(!result.ok)throw Error(result.error||'Live sharing could not update.');}
async function flush(){if(!initialized||!localStorage.getItem('bedo-auth-session')||localStorage.getItem('bedo-sync-pending')!=='true')return;if(!window.BedoAuth.hasDriveAccess()){notify('local','Autosaved on this device. Connect Google Drive when you want to sync other devices.');return;}if(busy){clearTimeout(timer);timer=setTimeout(flush,500);return;}if(!navigator.onLine){notify('pending','Autosaved on this device. Waiting for internet.');return;}busy=true;let snapshot=data(),signature=JSON.stringify(snapshot);notify('saving','Autosaved here. Comparing with Google Drive…');try{await updateLiveShare(snapshot);const cloud=await loadDrive(),remoteTime=Date.parse(cloud?.updatedAt||cloud?.savedAt||0),lastSeen=Date.parse(localStorage.getItem('bedo-last-sync')||0);if(cloud&&remoteTime>lastSeen){snapshot=merge(snapshot,cloud);restore(snapshot);localStorage.setItem('bedo-sync-pending','true');signature=JSON.stringify(data());await updateLiveShare(snapshot);}const savedAt=await saveDrive(snapshot);localStorage.setItem('bedo-last-sync',savedAt);if(JSON.stringify(data())===signature){localStorage.removeItem('bedo-sync-pending');notify('saved','Saved privately in your Google Drive.');}else notify('pending','New edits are waiting to save.');}catch(error){notify('error','Autosaved on this device only. '+error.message);}finally{busy=false;if(localStorage.getItem('bedo-sync-pending')==='true'&&window.BedoAuth.hasDriveAccess())timer=setTimeout(flush,5000);}}
function changed(){localStorage.setItem('bedo-local-updated-at',new Date().toISOString());backupLocal();localStorage.setItem('bedo-sync-pending','true');notify('pending','Autosaved on this device. Waiting to save to your Google Drive…');clearTimeout(timer);timer=setTimeout(flush,350);}
function restore(cloud){backupLocal();Object.entries(keys).forEach(([k,v])=>localStorage.setItem(v,JSON.stringify(cloud[k]||[])));const prefs=(cloud.settings||[]).find(s=>s.id==='preferences');if(prefs){if(prefs.profile)localStorage.setItem('bedo-profile',JSON.stringify(prefs.profile));if(prefs.theme)localStorage.setItem('bedo-theme',JSON.stringify(prefs.theme));if(prefs.tour)localStorage.setItem('bedo-tour-state',JSON.stringify(prefs.tour));if(prefs.lastView)localStorage.setItem('bedo-last-view',JSON.stringify(prefs.lastView));}const stamp=cloud.updatedAt||cloud.savedAt;if(stamp)localStorage.setItem('bedo-local-updated-at',stamp);if(cloud.savedAt)localStorage.setItem('bedo-last-sync',cloud.savedAt);localStorage.setItem('bedo-sync-base',JSON.stringify(cloud));}
function merge(local,cloud){const localTime=Date.parse(local.updatedAt||0),cloudTime=Date.parse(cloud.updatedAt||cloud.savedAt||0),preferLocal=localTime>=cloudTime,merged={};for(const key of Object.keys(keys)){const first=preferLocal?cloud[key]:local[key],second=preferLocal?local[key]:cloud[key],map=new Map();for(const item of first||[])map.set(item.id||JSON.stringify(item),item);for(const item of second||[])map.set(item.id||JSON.stringify(item),item);merged[key]=[...map.values()];}merged.settings=preferLocal?(local.settings||cloud.settings):(cloud.settings||local.settings);merged.updatedAt=new Date().toISOString();return merged;}
async function initialize(interactive=false){if(!localStorage.getItem('bedo-auth-session')){initialized=true;return true;}initialized=true;if(!interactive&&!window.BedoAuth.hasDriveAccess()){notify('local','Signed in. Restored where you left off on this device.');dispatchEvent(new Event('bedo-workspace-ready'));return true;}notify('loading','Comparing this device with your private Google Drive data…');try{await window.BedoAuth.requestDriveAccess(interactive);const cloud=await loadDrive(),local=data(),hasCloud=Boolean(cloud&&(Object.keys(keys).some(k=>(cloud[k]||[]).length)||(cloud.settings||[]).length)),hasLocal=Object.keys(keys).some(k=>(local[k]||[]).length);if(hasCloud&&hasLocal){const localTime=Date.parse(local.updatedAt||0),cloudTime=Date.parse(cloud.updatedAt||cloud.savedAt||0),pending=localStorage.getItem('bedo-sync-pending')==='true';if(pending||localTime>cloudTime){const combined=merge(local,cloud);restore(combined);localStorage.setItem('bedo-sync-pending','true');await flush();}else restore(cloud);}else if(hasCloud)restore(cloud);else{changed();await flush();}if(localStorage.getItem('bedo-sync-pending')!=='true')notify('saved','This device and Google Drive are up to date.');dispatchEvent(new Event('bedo-workspace-ready'));return true;}catch(error){notify('permission','Autosaved on this device. Connect Google Drive on this device to sync it.');return !interactive;}}
async function connect(){return initialize(true);}
async function refresh(){if(busy||!navigator.onLine||!localStorage.getItem('bedo-auth-session')||!window.BedoAuth.hasDriveAccess())return;if(localStorage.getItem('bedo-sync-pending')==='true'){await flush();return;}try{const cloud=await loadDrive(),remote=Date.parse(cloud?.updatedAt||cloud.savedAt||0),local=Date.parse(localStorage.getItem('bedo-local-updated-at')||0);if(cloud&&remote>local){restore(cloud);notify('saved','Updated from your Google Drive on this device.');dispatchEvent(new Event('bedo-workspace-ready'));}}catch(error){notify('permission','Autosaved on this device. Connect Google Drive on this device to sync it.');}}
async function saveNow(){if(!window.BedoAuth.hasDriveAccess())return connect();return flush();}
window.BedoSync={getStatus:()=>status,changed,saveNow,initialize,connect,refresh,exportData:data};window.BedoSync.ready=initialize(false);addEventListener('online',()=>{flush();refresh();});addEventListener('focus',refresh);addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh();});setInterval(()=>{flush();refresh();},5000);
})();
